import java.util.Random;
import java.util.Vector;
import javax.swing.JOptionPane;

/*
	 * To change this license header, choose License Headers in Project Properties.
	 * To change this template file, choose Tools | Templates
	 * and open the template in the editor.
	 */

	/**
	 *
	 * @author reyes
	 */
	@SuppressWarnings("serial")
	public class Game3 extends javax.swing.JFrame  {

		Vector<Integer> areas = null;
		Vector<Integer> areas2 = null;
		int ayuda = 3; 
	    /**
	     * Creates new form Game3
	     */
	    public Game3() {
	        areas = new Vector<Integer>(MainController.getInstance().tam());
	        int c = 0;
	        int var = 20;
			for (int i = 0; i < MainController.getInstance().tam(); ++i){
				areas.add(c);
				c += var;
				if (c >= 255){
					var += 10;
					if (var >= 255) var = 20;
					c = 0;
				}
			}
			areas2 = new Vector<Integer>(MainController.getInstance().tam());
		    c = 255;
		    var = 40;
			for (int i = 1; i <= MainController.getInstance().tam(); ++i){
				areas2.add(c);
				c -= var;
				if (c >= 255){
					var += 30; 
					if (var >= 255) var = 40;
					c = 0;
				}
			}
	    	initComponents();
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	    	 jInternalFrame1 = new javax.swing.JInternalFrame();
	         jLabel1 = new javax.swing.JLabel();
	         jTextField1 = new javax.swing.JTextField();
	         jTextField2 = new javax.swing.JTextField();
	         jTextField3 = new javax.swing.JTextField();
	         jTextField4 = new javax.swing.JTextField();
	         jTextField5 = new javax.swing.JTextField();
	         jTextField6 = new javax.swing.JTextField();
	         jTextField7 = new javax.swing.JTextField();
	         jTextField8 = new javax.swing.JTextField();
	         jTextField9 = new javax.swing.JTextField();
	         jButton1 = new javax.swing.JButton();
	         jButton3 = new javax.swing.JButton();
	         jButton4 = new javax.swing.JButton();
	         jButton2 = new javax.swing.JButton();
	         jLabel2 = new javax.swing.JLabel();
	         jLabel3 = new javax.swing.JLabel();
	         jLabel4 = new javax.swing.JLabel();
	         jLabel5 = new javax.swing.JLabel();
	         jLabel6 = new javax.swing.JLabel();
	         jLabel7 = new javax.swing.JLabel();
	         jLabel8 = new javax.swing.JLabel();
	         jLabel9 = new javax.swing.JLabel();
	         jLabel10 = new javax.swing.JLabel();
	         jButton5 = new javax.swing.JButton();
	         jButton6 = new javax.swing.JButton();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

	        jInternalFrame1.setVisible(true);

	        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
	        jLabel1.setText("Kenken");
	        
	        
	        jLabel2.setText(MainController.getInstance().areaTipo(0,0));
	        jLabel3.setText(MainController.getInstance().areaTipo(0,1));
	        jLabel4.setText(MainController.getInstance().areaTipo(0,2));
	        jLabel5.setText(MainController.getInstance().areaTipo(1,0));
	        jLabel6.setText(MainController.getInstance().areaTipo(1,1));
	        jLabel7.setText(MainController.getInstance().areaTipo(1,2));
	        jLabel8.setText(MainController.getInstance().areaTipo(2,0));
	        jLabel9.setText(MainController.getInstance().areaTipo(2,1));
	        jLabel10.setText(MainController.getInstance().areaTipo(2,2));
	        
	        jTextField1.setBackground(new java.awt.Color(((int) areas.get(MainController.getInstance().area(0,0))), ((int) areas2.get(MainController.getInstance().area(0,0))), 255));
	        jTextField1.setPreferredSize(new java.awt.Dimension(44, 22));
	        jTextField1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField1ActionPerformed(evt);
	            }
	        });

	        jTextField2.setBackground(new java.awt.Color(((int) areas.get(MainController.getInstance().area(0,1))), ((int) areas2.get(MainController.getInstance().area(0,1))), 255));
	        jTextField2.setPreferredSize(new java.awt.Dimension(44, 22));
	        jTextField2.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField2ActionPerformed(evt);
	            }
	        });

	        jTextField3.setBackground(new java.awt.Color(((int) areas.get(MainController.getInstance().area(0,2))), ((int) areas2.get(MainController.getInstance().area(0,2))), 255));
	        jTextField3.setPreferredSize(new java.awt.Dimension(44, 22));
	        jTextField3.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField3ActionPerformed(evt);
	            }
	        });

	        jTextField4.setBackground(new java.awt.Color(((int) areas.get(MainController.getInstance().area(1,0))), ((int) areas2.get(MainController.getInstance().area(1,0))), 255));
	        jTextField4.setPreferredSize(new java.awt.Dimension(44, 22));
	        jTextField4.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField4ActionPerformed(evt);
	            }
	        });

	        jTextField5.setBackground(new java.awt.Color(((int) areas.get(MainController.getInstance().area(1,1))), ((int) areas2.get(MainController.getInstance().area(1,1))), 255));
	        jTextField5.setPreferredSize(new java.awt.Dimension(44, 22));
	        jTextField5.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField5ActionPerformed(evt);
	            }
	        });

	        jTextField6.setBackground(new java.awt.Color(((int) areas.get(MainController.getInstance().area(1,2))), ((int) areas2.get(MainController.getInstance().area(1,2))), 255));
	        jTextField6.setPreferredSize(new java.awt.Dimension(44, 22));
	        jTextField6.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField6ActionPerformed(evt);
	            }
	        });

	        
	        jTextField7.setBackground(new java.awt.Color(((int) areas.get(MainController.getInstance().area(2,0))), ((int) areas2.get(MainController.getInstance().area(2,0))), 255));
	        jTextField7.setPreferredSize(new java.awt.Dimension(44, 22));
	        jTextField7.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField7ActionPerformed(evt);
	            }
	        });

	        
	        jTextField8.setBackground(new java.awt.Color(((int) areas.get(MainController.getInstance().area(2,1))), ((int) areas2.get(MainController.getInstance().area(2,1))), 255));
	        jTextField8.setPreferredSize(new java.awt.Dimension(44, 22));
	        jTextField8.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField8ActionPerformed(evt);
	            }
	        });

	        
	        jTextField9.setBackground(new java.awt.Color(((int) areas.get(MainController.getInstance().area(2,2))), ((int) areas2.get(MainController.getInstance().area(2,2))), 255));
	        jTextField9.setPreferredSize(new java.awt.Dimension(44, 22));
	        jTextField9.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField9ActionPerformed(evt);
	            }
	        });


	        jButton1.setText("Resoldre");
	        jButton1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton1ActionPerformed(evt);
	            }
	        });
	        jButton3.setText("Guardar");
	        jButton3.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton3ActionPerformed(evt);
	            }
	        });

	        jButton4.setText("Sortir");
	        jButton4.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton4ActionPerformed(evt);
	            }
	        });
	        
	        jButton2.setText("Ajuda");
	        jButton2.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton2ActionPerformed(evt);
	            }
	        });

	        jButton5.setText("Clear");
	        jButton5.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton5ActionPerformed(evt);
	            }
	        });

	        jButton6.setText("Rendir-se");
	        jButton6.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton6ActionPerformed(evt);
	            }
	        });

	        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
	        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
	        jInternalFrame1Layout.setHorizontalGroup(
	            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
	                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
	                        .addGap(74, 74, 74)
	                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                                .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                            .addComponent(jLabel2)
	                            .addComponent(jLabel3)
	                            .addComponent(jLabel4))
	                        .addGap(45, 45, 45)
	                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                            .addComponent(jLabel5)
	                            .addComponent(jLabel7)
	                            .addComponent(jLabel6))
	                        .addGap(45, 45, 45)
	                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                .addComponent(jLabel8)
	                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                    .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                                        .addComponent(jLabel9)
	                                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
	                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
	                                .addComponent(jLabel10)
	                                .addGap(2, 2, 2))))
	                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
	                        .addContainerGap()
	                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
	                                .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
	                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(jButton2)
	                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
	                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
	                .addGap(34, 34, 34))
	        );
	        jInternalFrame1Layout.setVerticalGroup(
	            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jInternalFrame1Layout.createSequentialGroup()
	                .addContainerGap()
	                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(13, 13, 13)
	                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jButton2))
	                .addGap(2, 2, 2)
	                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel2)
	                    .addComponent(jLabel5)
	                    .addComponent(jLabel8))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(6, 6, 6)
	                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel3)
	                    .addComponent(jLabel6)
	                    .addComponent(jLabel9))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel4)
	                    .addComponent(jLabel7)
	                    .addComponent(jLabel10))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
	                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jButton1)
	                    .addComponent(jButton5))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jButton6))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(jButton4)
	                .addGap(30, 30, 30))
	        );

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(0, 0, Short.MAX_VALUE))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(0, 0, Short.MAX_VALUE))
	        );

	    	int a = MainController.getInstance().num(0,0);
	    	if (a > 0) jTextField1.setText(Integer.toString(a));
		    a = MainController.getInstance().num(0,2);
		    if (a != -1) jTextField3.setText(Integer.toString(a));
	    	a = MainController.getInstance().num(0,1);
	    	if (a != -1) jTextField2.setText(Integer.toString(a));
	    	a = MainController.getInstance().num(1,0);
	    	if (a != -1) jTextField4.setText(Integer.toString(a));
	    	a = MainController.getInstance().num(1,1);
	    	if (a != -1) jTextField5.setText(Integer.toString(a));
	    	a = MainController.getInstance().num(1,2);
	    	if (a != -1) jTextField6.setText(Integer.toString(a));
	    	a = MainController.getInstance().num(2,0);
	    	if (a != -1) jTextField7.setText(Integer.toString(a));
	    	a = MainController.getInstance().num(2,1);
	    	if (a != -1) jTextField8.setText(Integer.toString(a));
	    	a = MainController.getInstance().num(2,2);
	    	if (a != -1) jTextField9.setText(Integer.toString(a));
	        pack();
	    }// </editor-fold>
	    
	    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
	        // TODO add your handling code here:
	    	if (ayuda > 0){
		    	Random r = new Random();
		    	Boolean ok = false;
		    	while (! ok){
		    		int var = r.nextInt();
		    		var = Math.abs(var);
		    		var = var%3;
		    		int a = MainController.getInstance().num(var,var);
		    		if (a == -1) {
		    			int b = MainController.getInstance().show(var,var);
		    			MainController.getInstance().posar_pos(var, var, String.valueOf(b));
		    			int c = MainController.getInstance().num(0,0);
		    	    	if (c > 0) jTextField1.setText(Integer.toString(c));
		    		    c = MainController.getInstance().num(0,2);
		    		    if (c != -1) jTextField3.setText(Integer.toString(c));
		    	    	c = MainController.getInstance().num(0,1);
		    	    	if (c != -1) jTextField2.setText(Integer.toString(c));
		    	    	c = MainController.getInstance().num(1,0);
		    	    	if (c != -1) jTextField4.setText(Integer.toString(c));
		    	    	c = MainController.getInstance().num(1,1);
		    	    	if (c != -1) jTextField5.setText(Integer.toString(c));
		    	    	c = MainController.getInstance().num(1,2);
		    	    	if (c != -1) jTextField6.setText(Integer.toString(c));
		    	    	c = MainController.getInstance().num(2,0);
		    	    	if (c != -1) jTextField7.setText(Integer.toString(c));
		    	    	c = MainController.getInstance().num(2,1);
		    	    	if (c != -1) jTextField8.setText(Integer.toString(c));
		    	    	c = MainController.getInstance().num(2,2);
		    	    	if (c != -1) jTextField9.setText(Integer.toString(c));
		    			ok = true;
		    		}
		    	}
		    	--ayuda;
	    	}
	    	else{
	    		JOptionPane.showMessageDialog(this, "Ja no pots tenir més ajudes");
	    	}
	    }    
	    
	    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
	        // TODO add your handling code here:
	    	MainController.getInstance().neteja();
	    	if(!MainController.getInstance().fija(0, 0)) jTextField1.setText("");
	    	if(!MainController.getInstance().fija(0, 1)) jTextField3.setText("");
	    	if(!MainController.getInstance().fija(0, 2)) jTextField2.setText("");
	    	if(!MainController.getInstance().fija(1, 0)) jTextField4.setText("");
	    	if(!MainController.getInstance().fija(1, 1)) jTextField5.setText("");
	    	if(!MainController.getInstance().fija(1, 2)) jTextField6.setText("");
	    	if(!MainController.getInstance().fija(2, 0)) jTextField7.setText("");
	    	if(!MainController.getInstance().fija(2, 1)) jTextField8.setText("");
	    	if(!MainController.getInstance().fija(2, 2)) jTextField9.setText("");
	    	
	    }                                        

	    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
	        // TODO add your handling code here:
	    	jTextField1.setText(Integer.toString(MainController.getInstance().show(0,0)));
		    jTextField3.setText(Integer.toString(MainController.getInstance().show(0,2)));
	    	jTextField2.setText(Integer.toString(MainController.getInstance().show(0,1)));
	    	jTextField4.setText(Integer.toString(MainController.getInstance().show(1,0)));
	    	jTextField5.setText(Integer.toString(MainController.getInstance().show(1,1)));
	    	jTextField6.setText(Integer.toString(MainController.getInstance().show(1,2)));
	    	jTextField7.setText(Integer.toString(MainController.getInstance().show(2,0)));
	    	jTextField8.setText(Integer.toString(MainController.getInstance().show(2,1)));
	    	jTextField9.setText(Integer.toString(MainController.getInstance().show(2,2)));
	    	JOptionPane.showMessageDialog(this, ":(");
	    	Menu f =new Menu();
    		f.setVisible(true);
    		dispose();
	    } 
	    
	    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
	        // TODO add your handling code here:
	    	if (MainController.getInstance().comp()){
				JOptionPane.showMessageDialog(this, "FELICITATS!!");
				if (!MainController.getInstance().es_guest()){
					MainController.getInstance().actualizar_punt();
					MainController.getInstance().delete_game();
				}
				Menu f =new Menu();
				f.setVisible(true);
				dispose();
			}
	    	else{
	    		JOptionPane.showMessageDialog(this, "Torna, esta malament :'(");
	    	}
	    }      
	    
   private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {                                            
		// TODO add your handling code here: 0 2 
		//actualitzar temps,es a dir, al <labeltemps>.setText(Long.toString(MainController.getInstance().getTiempo()));
		if (! MainController.getInstance().fija(0,2)){
			int valor = Integer.parseInt(jTextField3.getText());
			if((valor <= 3 && valor >= 1) || valor == -1 ){
				MainController.getInstance().posar_pos(0,2,jTextField3.getText());
				if(valor != -1){
					jTextField3.setText(Integer.toString(valor));
				}else{
					jTextField3.setText("");
				}
			}else{
				JOptionPane.showMessageDialog(this, "El valor ha de ser o be -1 o entre 1 i 3");
			}
		}else{
			jTextField3.setText(Integer.toString(MainController.getInstance().num(0, 2)));
		}  
	}                                           

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
		// TODO add your handling code here:   0 0
		if (! MainController.getInstance().fija(0,0)){
			int valor = Integer.parseInt(jTextField1.getText());
			if((valor <= 3 && valor >= 1) || valor == -1 ){
				MainController.getInstance().posar_pos(0,0,jTextField1.getText());
				if(valor != -1){
					jTextField1.setText(Integer.toString(valor));
				}else{
					jTextField1.setText("");
				}
			}else{
				JOptionPane.showMessageDialog(this, "El valor ha de ser o be -1 o entre 1 i 3");
			}
		}else{
			jTextField1.setText(Integer.toString(MainController.getInstance().num(0, 0)));
		}  
	}                                           

	private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
		// TODO add your handling code here: 0 1
		if (! MainController.getInstance().fija(0,1)){
			int valor = Integer.parseInt(jTextField2.getText());
			if((valor <= 3 && valor >= 1) || valor == -1 ){
				MainController.getInstance().posar_pos(0,1,jTextField2.getText());
				if(valor != -1){
					jTextField2.setText(Integer.toString(valor));
				}else{
					jTextField2.setText("");
				}
			}else{
				JOptionPane.showMessageDialog(this, "El valor ha de ser o be -1 o entre 1 i 3");
			}
		}else{
			jTextField2.setText(Integer.toString(MainController.getInstance().num(0, 1)));
		}  
	}                                           

	private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {                                            
		// TODO add your handling code here: 1 0
		if (! MainController.getInstance().fija(1,0)){
			int valor = Integer.parseInt(jTextField4.getText());
			if((valor <= 3 && valor >= 1) || valor == -1 ){
				MainController.getInstance().posar_pos(1,0,jTextField4.getText());
				if(valor != -1){
					jTextField4.setText(Integer.toString(valor));
				}else{
					jTextField4.setText("");
				}
			}else{
				JOptionPane.showMessageDialog(this, "El valor ha de ser o be -1 o entre 1 i 3");
			}
		}else{
			jTextField4.setText(Integer.toString(MainController.getInstance().num(1, 0)));
		}  
	}                                           

	private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {                                            
		// TODO add your handling code here: 1 1
		if (! MainController.getInstance().fija(1,1)){
			int valor = Integer.parseInt(jTextField5.getText());
			if((valor <= 3 && valor >= 1) || valor == -1 ){
				MainController.getInstance().posar_pos(1,1,jTextField5.getText());
				if(valor != -1){
					jTextField5.setText(Integer.toString(valor));
				}else{
					jTextField5.setText("");
				}
			}else{
				JOptionPane.showMessageDialog(this, "El valor ha de ser o be -1 o entre 1 i 3");
			}
		}else{
			jTextField5.setText(Integer.toString(MainController.getInstance().num(1, 1)));
		}  
	}

	private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {                                            
		// TODO add your handling code here: 1 2
		if (! MainController.getInstance().fija(1,2)){
			int valor = Integer.parseInt(jTextField6.getText());
			if((valor <= 3 && valor >= 1) || valor == -1 ){
				MainController.getInstance().posar_pos(1,2,jTextField6.getText());
				if(valor != -1){
					jTextField6.setText(Integer.toString(valor));
				}else{
					jTextField6.setText("");
				}
			}else{
				JOptionPane.showMessageDialog(this, "El valor ha de ser o be -1 o entre 1 i 3");
			}
		}else{
			jTextField6.setText(Integer.toString(MainController.getInstance().num(1, 2)));
		}  
	}

	private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {                                            
		// TODO add your handling code here: 2 0
		if (! MainController.getInstance().fija(2,0)){
			int valor = Integer.parseInt(jTextField7.getText());
			if((valor <= 3 && valor >= 1) || valor == -1 ){
				MainController.getInstance().posar_pos(2,0,jTextField7.getText());
				if(valor != -1){
					jTextField7.setText(Integer.toString(valor));
				}else{
					jTextField7.setText("");
				}
			}else{
				JOptionPane.showMessageDialog(this, "El valor ha de ser o be -1 o entre 1 i 3");
			}
		}else{
			jTextField7.setText(Integer.toString(MainController.getInstance().num(2, 0)));
		}                                  
	}

	private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {                                            
		// TODO add your handling code here: 2 1
		if (! MainController.getInstance().fija(2,1)){
			int valor = Integer.parseInt(jTextField8.getText());
			if((valor <= 3 && valor >= 1) || valor == -1 ){
				MainController.getInstance().posar_pos(2,1,jTextField8.getText());
				if(valor != -1){
					jTextField8.setText(Integer.toString(valor));
				}else{
					jTextField8.setText("");
				}
			}else{
				JOptionPane.showMessageDialog(this, "El valor ha de ser o be -1 o entre 1 i 3");
			}
		}else{
			jTextField8.setText(Integer.toString(MainController.getInstance().num(2, 1)));
		}
	}                                           

	private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {                                            
		// TODO add your handling code here: 2 2
		if (! MainController.getInstance().fija(2,2)){
			int valor = Integer.parseInt(jTextField9.getText());
			if((valor <= 3 && valor >= 1) || valor == -1 ){
				MainController.getInstance().posar_pos(2,2,jTextField9.getText());
				if(valor != -1){
					jTextField9.setText(Integer.toString(valor));
				}else{
					jTextField9.setText("");
				}
			}else{
				JOptionPane.showMessageDialog(this, "El valor ha de ser o be -1 o entre 1 i 3");
			}
		}else{
			jTextField9.setText(Integer.toString(MainController.getInstance().num(2, 2)));
		}
	}
	    
	    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
	        // TODO add your handling code here:
	    	/*guarda*/
	    	if (!MainController.getInstance().es_guest()){
	    		MainController.getInstance().save();
	    	}   
	    	else {
	    		JOptionPane.showMessageDialog(this, "Ets un convidat");
	    	}
	    }
	    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
	        // TODO add your handling code here:
			MainController.getInstance().sortir();
	    	Menu m = new Menu();
	    	m.setVisible(true);
	    	dispose();
	    }    
	    
	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        /* Set the Nimbus look and feel */
	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	         */
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(Game3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(Game3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(Game3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(Game3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        //</editor-fold>

	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new Game3().setVisible(true);
	            }
	        });
	    }

	    // Variables declaration - do not modify                     
	    private javax.swing.JButton jButton1;
	    private javax.swing.JButton jButton2;
	    private javax.swing.JButton jButton3;
	    private javax.swing.JButton jButton4;
	    private javax.swing.JButton jButton5;
	    private javax.swing.JButton jButton6;
	    private javax.swing.JInternalFrame jInternalFrame1;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel10;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JLabel jLabel4;
	    private javax.swing.JLabel jLabel5;
	    private javax.swing.JLabel jLabel6;
	    private javax.swing.JLabel jLabel7;
	    private javax.swing.JLabel jLabel8;
	    private javax.swing.JLabel jLabel9;
	    private javax.swing.JTextField jTextField1;
	    private javax.swing.JTextField jTextField2;
	    private javax.swing.JTextField jTextField3;
	    private javax.swing.JTextField jTextField4;
	    private javax.swing.JTextField jTextField5;
	    private javax.swing.JTextField jTextField6;
	    private javax.swing.JTextField jTextField7;
	    private javax.swing.JTextField jTextField8;
	    private javax.swing.JTextField jTextField9;
	    // End of variables declaration                   
	}

