import java.util.Vector;

import javax.swing.JButton;

/*
	 * To change this license header, choose License Headers in Project Properties.
	 * To change this template file, choose Tools | Templates
	 * and open the template in the editor.
	 */

	/**
	 *
	 * @author reyes
	 */
	public class Game3 extends javax.swing.JFrame {

		MainController mc = null;
		Vector<Integer> areas = null;
		Vector<Integer> areas2 = null;

	    /**
	     * Creates new form Game3
	     */
	    public Game3(MainController a) {
	        mc = a;
	        areas = new Vector<Integer>(mc.tam());
	        int c = 0;
			for (int i = 0; i < mc.tam(); ++i){
				areas.add(c);
				c += 20;
			}
			areas2 = new Vector<Integer>(mc.tam());
		    c = 255;
			for (int i = 0; i < mc.tam(); ++i){
				areas2.add(c);
				c -= 20;
			}
	    	initComponents();
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        jInternalFrame1 = new javax.swing.JInternalFrame();
	        jLabel1 = new javax.swing.JLabel();
	        jTextField1 = new javax.swing.JTextField();
	        jTextField2 = new javax.swing.JTextField();
	        jTextField3 = new javax.swing.JTextField();
	        jTextField4 = new javax.swing.JTextField();
	        jTextField5 = new javax.swing.JTextField();
	        jTextField6 = new javax.swing.JTextField();
	        jTextField7 = new javax.swing.JTextField();
	        jTextField8 = new javax.swing.JTextField();
	        jTextField9 = new javax.swing.JTextField();
	        jButton1 = new javax.swing.JButton();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

	        jInternalFrame1.setVisible(true);

	        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
	        jLabel1.setText("Kenken");
	        
	        
	        
	        
	        jTextField1.setBackground(new java.awt.Color(((int) areas.get(mc.area(0,0))), ((int) areas2.get(mc.area(0,0))), 255));
	        jTextField1.setPreferredSize(new java.awt.Dimension(44, 22));
	        jTextField1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField1ActionPerformed(evt);
	            }
	        });

	        jTextField2.setBackground(new java.awt.Color(((int) areas.get(mc.area(0,1))), ((int) areas2.get(mc.area(0,1))), 255));
	        jTextField2.setPreferredSize(new java.awt.Dimension(44, 22));
	        jTextField2.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField2ActionPerformed(evt);
	            }
	        });

	        jTextField3.setBackground(new java.awt.Color(((int) areas.get(mc.area(0,2))), ((int) areas2.get(mc.area(0,2))), 255));
	        jTextField3.setPreferredSize(new java.awt.Dimension(44, 22));
	        jTextField3.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField3ActionPerformed(evt);
	            }
	        });

	        jTextField4.setBackground(new java.awt.Color(((int) areas.get(mc.area(1,0))), ((int) areas2.get(mc.area(1,0))), 255));
	        jTextField4.setPreferredSize(new java.awt.Dimension(44, 22));
	        jTextField4.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField4ActionPerformed(evt);
	            }
	        });

	        jTextField5.setBackground(new java.awt.Color(((int) areas.get(mc.area(1,1))), ((int) areas2.get(mc.area(1,1))), 255));
	        jTextField5.setPreferredSize(new java.awt.Dimension(44, 22));
	        jTextField5.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField5ActionPerformed(evt);
	            }
	        });

	        jTextField6.setBackground(new java.awt.Color(((int) areas.get(mc.area(1,2))), ((int) areas2.get(mc.area(1,2))), 255));
	        jTextField6.setPreferredSize(new java.awt.Dimension(44, 22));
	        jTextField6.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField6ActionPerformed(evt);
	            }
	        });

	        
	        jTextField7.setBackground(new java.awt.Color(((int) areas.get(mc.area(2,0))), ((int) areas2.get(mc.area(2,0))), 255));
	        jTextField7.setPreferredSize(new java.awt.Dimension(44, 22));
	        jTextField7.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField7ActionPerformed(evt);
	            }
	        });

	        
	        jTextField8.setBackground(new java.awt.Color(((int) areas.get(mc.area(2,1))), ((int) areas2.get(mc.area(2,1))), 255));
	        jTextField8.setPreferredSize(new java.awt.Dimension(44, 22));
	        jTextField8.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField8ActionPerformed(evt);
	            }
	        });

	        
	        jTextField9.setBackground(new java.awt.Color(((int) areas.get(mc.area(2,2))), ((int) areas2.get(mc.area(2,2))), 255));
	        jTextField9.setPreferredSize(new java.awt.Dimension(44, 22));
	        jTextField9.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField9ActionPerformed(evt);
	            }
	        });


	        jButton1.setText("Resoldre");
	        jButton1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton1ActionPerformed(evt);
	            }
	        });
	        
	        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
	        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
	        jInternalFrame1Layout.setHorizontalGroup(
	            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jInternalFrame1Layout.createSequentialGroup()
	                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
	                        .addGap(74, 74, 74)
	                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                            .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                        .addGap(45, 45, 45)
	                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                            .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                        .addGap(51, 51, 51)
	                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                            .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
	                        .addContainerGap()
	                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                .addContainerGap(205, Short.MAX_VALUE))
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
	                .addGap(0, 0, Short.MAX_VALUE)
	                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                    .addComponent(jButton1)
	                .addGap(34, 34, 34))));
	        
	        jInternalFrame1Layout.setVerticalGroup(
	            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jInternalFrame1Layout.createSequentialGroup()
	                .addContainerGap()
	                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(14, 14, 14)
	                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(27, 27, 27)
	                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(29, 29, 29)
	                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
	                .addComponent(jButton1)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGap(62, 62, 62))
	        );

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(0, 0, Short.MAX_VALUE))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(0, 0, Short.MAX_VALUE))
	        );

	        pack();
	    }// </editor-fold> 
	    
	    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
	        // TODO add your handling code here:
	    	Jugar j = new Jugar(mc);
	    	if (j.comprobar()){
	    		Felicitats f =new Felicitats();
	    		f.setVisible(true);
	    		dispose();
	    	}
	    	else{
	    		Torna t =new Torna();
	    		t.setVisible(true);
	    	}
	    }      
	    
	    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {                                            
	        // TODO add your handling code here: 0 2 
	    	Jugar j = new Jugar(mc);
	    	j.poner(0,2,jTextField3.getText());
	    }                                           

	    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
	        // TODO add your handling code here:   0 0
	    	Jugar j = new Jugar(mc);
	    	j.poner(0,0,jTextField1.getText());
	    }                                           

	    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
	        // TODO add your handling code here: 0 1
	    	Jugar j = new Jugar(mc);
	    	j.poner(0,1,jTextField2.getText());
	    }                                           

	    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {                                            
	        // TODO add your handling code here: 1 0
	    	Jugar j = new Jugar(mc);
	    	j.poner(1,0,jTextField4.getText());
	    }                                           

	    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {                                            
	        // TODO add your handling code here: 1 1
	    	Jugar j = new Jugar(mc);
	    	j.poner(1,1,jTextField5.getText());
	    }                                           

	    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {                                            
	        // TODO add your handling code here: 1 2
	    	Jugar j = new Jugar(mc);
	    	j.poner(1,2,jTextField6.getText());
	    }                                           

	    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {                                            
	        // TODO add your handling code here: 2 0
	    	Jugar j = new Jugar(mc);
	    	j.poner(2,0,jTextField7.getText());
	    }                                           

	    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {                                            
	        // TODO add your handling code here: 2 1
	    	Jugar j = new Jugar(mc);
	    	j.poner(2,1,jTextField8.getText());
	    }                                           

	    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {                                            
	        // TODO add your handling code here: 2 2
	    	Jugar j = new Jugar(mc);
	    	j.poner(2,2,jTextField9.getText());
	    }                                           

	   /* private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
	    	Jugar j = new Jugar(mc);
	    	if (j.comprobar()){
	    		Felicitats f =new Felicitats();
	    		f.setVisible(true);
	    		dispose();
	    	}
	    	else{
	    		Torna t =new Torna();
	    		t.setVisible(true);
	    	}
	    }  */ 
	    
	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        /* Set the Nimbus look and feel */
	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	         */
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(Game3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(Game3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(Game3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(Game3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        //</editor-fold>

	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new Game3(null).setVisible(true);
	            }
	        });
	    }

	    // Variables declaration - do not modify                     
	    private javax.swing.JButton jButton1;
	    private javax.swing.JInternalFrame jInternalFrame1;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JTextField jTextField1;
	    private javax.swing.JTextField jTextField2;
	    private javax.swing.JTextField jTextField3;
	    private javax.swing.JTextField jTextField4;
	    private javax.swing.JTextField jTextField5;
	    private javax.swing.JTextField jTextField6;
	    private javax.swing.JTextField jTextField7;
	    private javax.swing.JTextField jTextField8;
	    private javax.swing.JTextField jTextField9;
	    // End of variables declaration                   
	}

